version: "3"
services:
  web:
    image: chksm/magnesium-web
    environment:
      - PUBLIC_URL=http://localhost:3000
      - PUBLIC_NAME=Magnesium
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
